on: [push]

jobs:
  dynamic_security_testing:
    runs-on: ubuntu-latest
    name: Scan live web app for security flaws
    steps:
      - uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Testing on Single URL
        uses: projectdiscovery/nuclei-action@main
        with:
          target: http://localhost:8080

      - name: Nuclei - Vulnerability Scan Severity critical,high,medium,low
        uses: projectdiscovery/nuclei-action@main
        with:
          target: http://localhost:8080
          flags: "-severity critical,high,medium,low -stats"

      - name: Dynamic Security Testing on Single URL 
        uses: projectdiscovery/nuclei-action@main
        with:
          target: http://localhost:8080 
          flags: "-headless  "              


      # - uses: actions/checkout@v2
      # - name: Dynamic Security Testing on Multiple URL
      #   uses: projectdiscovery/nuclei-action@main
      #   with:
      #     urls: ./github/workflows/list.txt

      # - name: Nuclei - Vulnerability Scan
      #   uses: projectdiscovery/nuclei-action@main
      #   with:
      #     urls: http://localhost:8080
      #     config: config.yaml
      #     report-config: issues.yaml


      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down

  # container_scanning:
  #   name: Scan Container for Security Issues
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Build an image from Dockerfile
  #       run: |
  #         docker build --file Dockerfile.app -t dvpwa.app:${{ github.sha }} .

  #     - name: Run Trivy vulnerability scanner
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         image-ref: 'dvpwa.app:${{ github.sha }}'
  #         format: 'table'
  #         exit-code: '1'
  #         ignore-unfixed: true
  #         vuln-type: 'os,library'
  #         severity: 'CRITICAL'
